package com.shunchang.yingyong.edu.base.db.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "updateLastTime".
 */
public class UpdateLastTime implements java.io.Serializable {

    private Long id;
    private String BaseType;
    private String BaseTimeSpan;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public UpdateLastTime() {
    }

    public UpdateLastTime(Long id) {
        this.id = id;
    }

    public UpdateLastTime(Long id, String BaseType, String BaseTimeSpan) {
        this.id = id;
        this.BaseType = BaseType;
        this.BaseTimeSpan = BaseTimeSpan;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getBaseType() {
        return BaseType;
    }

    public void setBaseType(String BaseType) {
        this.BaseType = BaseType;
    }

    public String getBaseTimeSpan() {
        return BaseTimeSpan;
    }

    public void setBaseTimeSpan(String BaseTimeSpan) {
        this.BaseTimeSpan = BaseTimeSpan;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
